### ISSUE TITLE
Prepare hackathon onboarding session

### ISSUE THREAD

**Issue by EdoPlantinga** [demodam/demodam.org#49]
https://docs.google.com/presentation/d/1ueLpnCIA06f05uuSTop8DU9olLb0M34iR_HrjsebRfI/edit#slide=id.gdc7252d228_1_247

**Comment by EdoPlantinga** [comment]
@AlbaRoza Did you manage to take a look at the doc?

**Comment by AlbaRoza** [comment]
> @AlbaRoza Did you manage to take a look at the doc?

I did but will add more details later today.
